version: "3"
services:
    web:
        image: nginx:latest
        container_name: nuvem_web
        volumes:
            - "./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - ".:/var/www/html"
        ports:
            - "8080:80"
        restart: always
        depends_on:
            - php
        networks:
            - nuvem_backend

    php:
        image: nanoninja/php-fpm
        container_name: nuvem_php
        restart: always
        user: www-data
        working_dir: /var/www/html
        volumes:
            - "./docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ".:/var/www/html"
        ports:
            - "9000:9000"
        depends_on:
            - mysqldb
        networks:
            - nuvem_backend

    mysqldb:
        image: mysql
        container_name: nuvem_mysql
        restart: always
        environment:
            - MYSQL_DATABASE=nuvem_shop
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=nuvem
            - MYSQL_PASSWORD=nuvem
        ports:
            - "8989:3306"
        volumes:
            - "./docker/data/db/mysql:/var/lib/mysql"
        networks:
            - nuvem_backend
networks:
    nuvem_backend:
        driver: bridge